web/router.ex
defmodule Earth.Router do
  use Earth.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  # This plug will look for a Guardian token in the session in the default location
  # Then it will attempt to load the resource found in the JWT.
  # If it doesn't find a JWT in the default location it doesn't do anything
  pipeline :browser_auth do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
  end

  # This pipeline if intended for API requests and looks for the JWT in the "Authorization" header
  # In this case, it should be prefixed with "Bearer" so that it's looking for
  # Authorization: Bearer <jwt>

  # pipeline :api_auth do
  #   plug Guardian.Plug.VerifyHeader, realm: "Bearer"
  #   plug Guardian.Plug.LoadResource
  # end

  scope "/", Earth do
    # We pipe this through the browser_auth to fetch logged in people
    # We pipe this through the impersonation_browser_auth to know if we're impersonating
    # We don't just pipe it through admin_browser_auth because that also loads the resource
    pipe_through [:browser, :browser_auth]

    get "/", PageController, :index
    delete "/logout", AuthController, :logout

    resources "/users", UserController
    resources "/authorizations", AuthorizationController
    resources "/tokens", TokenController

    # get "/private", PrivatePageController, :index
  end

  # This scope is the main authentication area for Ueberauth
  scope "/auth", Earth do
    pipe_through [:browser, :browser_auth] # Use the default browser stack

    get "/:identity", AuthController, :login
    get "/:identity/callback", AuthController, :callback
    post "/:identity/callback", AuthController, :callback
  end


  # Other scopes may use custom stacks.
  # scope "/api", Earth do
  #   pipe_through :api
  # end
end

web/views/layout_view.ex
defmodule Earth.LayoutView do
  use Earth.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Earth!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
          <nav role="navigation">
              <ul class="nav nav-pills pull-right btn-group-xs">
                  <%= render "login_bar.html", current_user: @current_user, conn: @conn %>
              </ul>
              <span class="logo"></span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <%= if @current_user do %>
          <%= render "navigation.html", current_user: @current_user, conn: @conn %>
      <% else %>
          <!-- <p class="alert alert-warning" role="alert">Not logged in</p> -->
      <% end %>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->

    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/layout/login_bar.html.eex
<%= if @current_user do %>
  <li>
    <%= link "Logout", to: auth_path(@conn, :logout), method: :delete, class: "btn btn-danger" %>
  </li>
  <%= if @conn.request_path != auth_path(@conn, :login, "identity") do %>
    <li>
      <%= link "Connect", to: auth_path(@conn, :login, "identity"), class: "btn btn-default"%>
    </li>
  <% end %>
<% else %>
  <li>
    <%= if @conn.request_path != auth_path(@conn, :login, "identity") do %>
      <%= link "Login", to: auth_path(@conn, :login, "identity"), class: "btn btn-primary"%>
    <% end %>
  </li>
<% end %>

web/templates/layout/navigation.html.eex
<ul class='nav nav-tabs'>
  <li role='presentation' class='<%#= active_on_current(@conn, private_page_path(@conn, :index)) %>'>
    <%#= link "Private", to: private_page_path(@conn, :index) %>
  </li>
  <li role='presentation' class='<%= active_on_current(@conn, authorization_path(@conn, :index)) %>'>
    <%= link "Authorizations", to: authorization_path(@conn, :index) %>
  </li>
  <li role='presentation' class='<%= active_on_current(@conn, token_path(@conn, :index)) %>'>
    <%= link "Tokens", to: token_path(@conn, :index) %>
  </li>
</ul>